- name: "Start 'linux' service, and enable it to start on boot"
  ansible.builtin.service:
    name: linux
    state: started
    enabled: true
  # changed_when: false
  become: true
  become_user: root

